### PR TITLE
Open vvvvolders feature

### PR DESCRIPTION
**Pull request by sebescudie**
Added a feature that allows to open vvvv related folders with a shortcut :

- SHIFT + ALT + V opens the running vvvv folder
- SHIFT + ALT + R opens the folder the active patch sits in

### CODE REVIEW

**Comment by velcrome** [comment]
you're on a roll! cool stuff, much appreciated.

will look into the PR and merge once i am back from my current job. should be at the end of the week.

**Comment by sebescudie** [comment]
Sweet, thank :)

**Comment by velcrome** [comment]
works nicely. 

I was thinking about changing the shortcut though, especially because the R-command is quite close to reloading a patch.
**F3** for patch, and **Alt+F3** for vvvv install maybe?

Something that struck me was your use of the IsActive module, which I have never used so far. What is it doing? I cannot tell the difference with the stripped down version of your module that you can see here.

showv4folders vvvv _2017 05 14-21 35 06

Of course I would prefer the slicker module, but not at every cost. 
Please tell me if it has any less functionality than what you worked for.

[ShowV4Folders (VVVV).zip](https://github.com/velcrome/vvvv-Patchbox/files/999669/ShowV4Folders.VVVV.zip)

**Comment by velcrome** [comment]
i pushed my considerations here as well:

https://github.com/velcrome/vvvv-Patchbox/commits/open_vvvvolders_feature

**Comment by sebescudie** [comment]
hey velcrome,

F3/Alt+F3 is fine, it's true that the sortcut I used can be missused.

Concerning the IsActive module, since we use a Keyboard (Desktop), I wanted to make sure vvvv has the focus so that OpenExplorer wouldn't trigger if you use the shortcut in an other application.

What do you think of that ?

Thanks for your concern !

seb

**Comment by velcrome** [comment]
Ah, I missed that one. Good thing I asked :)

**Comment by velcrome** [comment]
**Bonus**: Shift+F3 and Alt+Shift+F3 are used for opening custom directories.

**Pull request merged**
